version: '3.9'
services:
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/test.yml'
    volumes:
      - ./test.yml:/tmp/test.yml:ro
    ports:
      # Serve the mocked API locally as available on port 8080
      - '8080:4010'
